/*******************************************************************************
 * Copyright (c) 1991, 2021 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at https://www.eclipse.org/legal/epl-2.0/
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following
 * Secondary Licenses when the conditions for such availability set
 * forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
 * General Public License, version 2 with the GNU Classpath
 * Exception [1] and GNU General Public License, version 2 with the
 * OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/
package com.ibm.j9ddr.vm29.structure;

/**
 * Structure: J9MemoryInfo
 *
 * This stub class represents a class that can return in memory offsets
 * to VM C and C++ structures.
 *
 * This particular implementation exists only to allow StructurePointer code to
 * compile at development time.  This is never loaded at run time.
 *
 * At runtime generated byte codes returning actual offset values from the core file
 * will be loaded by the StructureClassLoader.
 */
public final class J9MemoryInfo {

	// VM Constants

	public static final long SIZEOF;

	// Offsets

	public static final int _availPhysicalOffset_;
	public static final int _availSwapOffset_;
	public static final int _availVirtualOffset_;
	public static final int _bufferedOffset_;
	public static final int _cachedOffset_;
	public static final int _hostAvailPhysicalOffset_;
	public static final int _hostBufferedOffset_;
	public static final int _hostCachedOffset_;
	public static final int _timestampOffset_;
	public static final int _totalPhysicalOffset_;
	public static final int _totalSwapOffset_;
	public static final int _totalVirtualOffset_;

	// Static Initializer

	private static final boolean RUNTIME = false;

	static {
		if (!RUNTIME) {
			throw new IllegalArgumentException("This stub class should not be on your classpath");
		}

		SIZEOF = 0;
		_availPhysicalOffset_ = 0;
		_availSwapOffset_ = 0;
		_availVirtualOffset_ = 0;
		_bufferedOffset_ = 0;
		_cachedOffset_ = 0;
		_hostAvailPhysicalOffset_ = 0;
		_hostBufferedOffset_ = 0;
		_hostCachedOffset_ = 0;
		_timestampOffset_ = 0;
		_totalPhysicalOffset_ = 0;
		_totalSwapOffset_ = 0;
		_totalVirtualOffset_ = 0;
	}

}
