/*******************************************************************************
 * Copyright (c) 1991, 2021 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at https://www.eclipse.org/legal/epl-2.0/
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following
 * Secondary Licenses when the conditions for such availability set
 * forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
 * General Public License, version 2 with the GNU Classpath
 * Exception [1] and GNU General Public License, version 2 with the
 * OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/
package com.ibm.j9ddr.vm29.structure;

/**
 * Structure: J9SharedCacheInfo
 *
 * This stub class represents a class that can return in memory offsets
 * to VM C and C++ structures.
 *
 * This particular implementation exists only to allow StructurePointer code to
 * compile at development time.  This is never loaded at run time.
 *
 * At runtime generated byte codes returning actual offset values from the core file
 * will be loaded by the StructureClassLoader.
 */
public final class J9SharedCacheInfo {

	// VM Constants

	public static final long SIZEOF;

	// Offsets

	public static final int _addrModeOffset_;
	public static final int _cacheSizeOffset_;
	public static final int _cacheTypeOffset_;
	public static final int _freeBytesOffset_;
	public static final int _isCompatibleOffset_;
	public static final int _isCorruptOffset_;
	public static final int _lastDetachOffset_;
	public static final int _layerOffset_;
	public static final int _modLevelOffset_;
	public static final int _nameOffset_;
	public static final int _os_semidOffset_;
	public static final int _os_shmidOffset_;
	public static final int _softMaxBytesOffset_;

	// Static Initializer

	private static final boolean RUNTIME = false;

	static {
		if (!RUNTIME) {
			throw new IllegalArgumentException("This stub class should not be on your classpath");
		}

		SIZEOF = 0;
		_addrModeOffset_ = 0;
		_cacheSizeOffset_ = 0;
		_cacheTypeOffset_ = 0;
		_freeBytesOffset_ = 0;
		_isCompatibleOffset_ = 0;
		_isCorruptOffset_ = 0;
		_lastDetachOffset_ = 0;
		_layerOffset_ = 0;
		_modLevelOffset_ = 0;
		_nameOffset_ = 0;
		_os_semidOffset_ = 0;
		_os_shmidOffset_ = 0;
		_softMaxBytesOffset_ = 0;
	}

}
