/*******************************************************************************
 * Copyright (c) 1991, 2021 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at https://www.eclipse.org/legal/epl-2.0/
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following
 * Secondary Licenses when the conditions for such availability set
 * forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
 * General Public License, version 2 with the GNU Classpath
 * Exception [1] and GNU General Public License, version 2 with the
 * OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/
package com.ibm.j9ddr.vm29.structure;

/**
 * Structure: J9ZipCentralEnd
 *
 * This stub class represents a class that can return in memory offsets
 * to VM C and C++ structures.
 *
 * This particular implementation exists only to allow StructurePointer code to
 * compile at development time.  This is never loaded at run time.
 *
 * At runtime generated byte codes returning actual offset values from the core file
 * will be loaded by the StructureClassLoader.
 */
public final class J9ZipCentralEnd {

	// VM Constants

	public static final long SIZEOF;

	// Offsets

	public static final int _commentOffset_;
	public static final int _commentLengthOffset_;
	public static final int _dirOffsetOffset_;
	public static final int _dirSizeOffset_;
	public static final int _dirStartDiskOffset_;
	public static final int _diskNumberOffset_;
	public static final int _endCentralDirRecordPositionOffset_;
	public static final int _thisDiskEntriesOffset_;
	public static final int _totalEntriesOffset_;

	// Static Initializer

	private static final boolean RUNTIME = false;

	static {
		if (!RUNTIME) {
			throw new IllegalArgumentException("This stub class should not be on your classpath");
		}

		SIZEOF = 0;
		_commentOffset_ = 0;
		_commentLengthOffset_ = 0;
		_dirOffsetOffset_ = 0;
		_dirSizeOffset_ = 0;
		_dirStartDiskOffset_ = 0;
		_diskNumberOffset_ = 0;
		_endCentralDirRecordPositionOffset_ = 0;
		_thisDiskEntriesOffset_ = 0;
		_totalEntriesOffset_ = 0;
	}

}
